# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: paymentService.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='paymentService.proto',
  package='ordermgt',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x14paymentService.proto\x12\x08ordermgt\" \n\nCustomerID\x12\x12\n\ncustomerID\x18\x01 \x01(\x05\"\xc1\x01\n\x13\x43ustomerInformation\x12\x12\n\ncustomerID\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07surname\x18\x03 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x04 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x05 \x01(\t\x12\x10\n\x08postcode\x18\x06 \x01(\t\x12\x13\n\x0bphonenumber\x18\x07 \x01(\x05\x12\x10\n\x08province\x18\x08 \x01(\t\x12\x1c\n\x14\x64\x65siredPaymentMethod\x18\t \x01(\t\"\x07\n\x05\x45mpty\"\x1e\n\x0ePaymentOptions\x12\x0c\n\x04name\x18\x01 \x03(\t\"1\n\x0b\x43redentials\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x18\n\x06Status\x12\x0e\n\x06result\x18\x01 \x01(\t\"\xa6\x01\n\x10OrderInformation\x12\x12\n\ncustomerID\x18\x01 \x01(\x05\x12\x0f\n\x07orderID\x18\x02 \x01(\x05\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x02\x12\x0c\n\x04paid\x18\x04 \x01(\t\x12\x17\n\x0fshipmentAddress\x18\x05 \x01(\t\x12\x17\n\x0fshipmentCountry\x18\x06 \x01(\t\x12\x0c\n\x04name\x18\x07 \x01(\t\x12\x0f\n\x07surname\x18\x08 \x01(\t\"\x1b\n\tSucceeded\x12\x0e\n\x06result\x18\x01 \x01(\x08\"\'\n\x0bMailMessage\x12\x18\n\x10\x63onfirmationMail\x18\x01 \x01(\t2\xfc\x02\n\x0ePaymentService\x12O\n\x16GetPersonalInformation\x12\x14.ordermgt.CustomerID\x1a\x1d.ordermgt.CustomerInformation\"\x00\x12@\n\x11GetPaymentOptions\x12\x0f.ordermgt.Empty\x1a\x18.ordermgt.PaymentOptions\"\x00\x12\x44\n\x17\x43heckPaymentCredentials\x12\x15.ordermgt.Credentials\x1a\x10.ordermgt.Status\"\x00\x12H\n\x13\x43reatePaymentRecord\x12\x1a.ordermgt.OrderInformation\x1a\x13.ordermgt.Succeeded\"\x00\x12G\n\x10SendConfirmation\x12\x1a.ordermgt.OrderInformation\x1a\x15.ordermgt.MailMessage\"\x00\x62\x06proto3'
)




_CUSTOMERID = _descriptor.Descriptor(
  name='CustomerID',
  full_name='ordermgt.CustomerID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='customerID', full_name='ordermgt.CustomerID.customerID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=66,
)


_CUSTOMERINFORMATION = _descriptor.Descriptor(
  name='CustomerInformation',
  full_name='ordermgt.CustomerInformation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='customerID', full_name='ordermgt.CustomerInformation.customerID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='ordermgt.CustomerInformation.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='surname', full_name='ordermgt.CustomerInformation.surname', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='address', full_name='ordermgt.CustomerInformation.address', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='country', full_name='ordermgt.CustomerInformation.country', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='postcode', full_name='ordermgt.CustomerInformation.postcode', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='phonenumber', full_name='ordermgt.CustomerInformation.phonenumber', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='province', full_name='ordermgt.CustomerInformation.province', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='desiredPaymentMethod', full_name='ordermgt.CustomerInformation.desiredPaymentMethod', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=262,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='ordermgt.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=264,
  serialized_end=271,
)


_PAYMENTOPTIONS = _descriptor.Descriptor(
  name='PaymentOptions',
  full_name='ordermgt.PaymentOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ordermgt.PaymentOptions.name', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=273,
  serialized_end=303,
)


_CREDENTIALS = _descriptor.Descriptor(
  name='Credentials',
  full_name='ordermgt.Credentials',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='ordermgt.Credentials.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='ordermgt.Credentials.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=305,
  serialized_end=354,
)


_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='ordermgt.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='ordermgt.Status.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=356,
  serialized_end=380,
)


_ORDERINFORMATION = _descriptor.Descriptor(
  name='OrderInformation',
  full_name='ordermgt.OrderInformation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='customerID', full_name='ordermgt.OrderInformation.customerID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orderID', full_name='ordermgt.OrderInformation.orderID', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='ordermgt.OrderInformation.amount', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='paid', full_name='ordermgt.OrderInformation.paid', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shipmentAddress', full_name='ordermgt.OrderInformation.shipmentAddress', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shipmentCountry', full_name='ordermgt.OrderInformation.shipmentCountry', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='ordermgt.OrderInformation.name', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='surname', full_name='ordermgt.OrderInformation.surname', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=383,
  serialized_end=549,
)


_SUCCEEDED = _descriptor.Descriptor(
  name='Succeeded',
  full_name='ordermgt.Succeeded',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='ordermgt.Succeeded.result', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=551,
  serialized_end=578,
)


_MAILMESSAGE = _descriptor.Descriptor(
  name='MailMessage',
  full_name='ordermgt.MailMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='confirmationMail', full_name='ordermgt.MailMessage.confirmationMail', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=580,
  serialized_end=619,
)

DESCRIPTOR.message_types_by_name['CustomerID'] = _CUSTOMERID
DESCRIPTOR.message_types_by_name['CustomerInformation'] = _CUSTOMERINFORMATION
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['PaymentOptions'] = _PAYMENTOPTIONS
DESCRIPTOR.message_types_by_name['Credentials'] = _CREDENTIALS
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
DESCRIPTOR.message_types_by_name['OrderInformation'] = _ORDERINFORMATION
DESCRIPTOR.message_types_by_name['Succeeded'] = _SUCCEEDED
DESCRIPTOR.message_types_by_name['MailMessage'] = _MAILMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CustomerID = _reflection.GeneratedProtocolMessageType('CustomerID', (_message.Message,), {
  'DESCRIPTOR' : _CUSTOMERID,
  '__module__' : 'paymentService_pb2'
  # @@protoc_insertion_point(class_scope:ordermgt.CustomerID)
  })
_sym_db.RegisterMessage(CustomerID)

CustomerInformation = _reflection.GeneratedProtocolMessageType('CustomerInformation', (_message.Message,), {
  'DESCRIPTOR' : _CUSTOMERINFORMATION,
  '__module__' : 'paymentService_pb2'
  # @@protoc_insertion_point(class_scope:ordermgt.CustomerInformation)
  })
_sym_db.RegisterMessage(CustomerInformation)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'paymentService_pb2'
  # @@protoc_insertion_point(class_scope:ordermgt.Empty)
  })
_sym_db.RegisterMessage(Empty)

PaymentOptions = _reflection.GeneratedProtocolMessageType('PaymentOptions', (_message.Message,), {
  'DESCRIPTOR' : _PAYMENTOPTIONS,
  '__module__' : 'paymentService_pb2'
  # @@protoc_insertion_point(class_scope:ordermgt.PaymentOptions)
  })
_sym_db.RegisterMessage(PaymentOptions)

Credentials = _reflection.GeneratedProtocolMessageType('Credentials', (_message.Message,), {
  'DESCRIPTOR' : _CREDENTIALS,
  '__module__' : 'paymentService_pb2'
  # @@protoc_insertion_point(class_scope:ordermgt.Credentials)
  })
_sym_db.RegisterMessage(Credentials)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'paymentService_pb2'
  # @@protoc_insertion_point(class_scope:ordermgt.Status)
  })
_sym_db.RegisterMessage(Status)

OrderInformation = _reflection.GeneratedProtocolMessageType('OrderInformation', (_message.Message,), {
  'DESCRIPTOR' : _ORDERINFORMATION,
  '__module__' : 'paymentService_pb2'
  # @@protoc_insertion_point(class_scope:ordermgt.OrderInformation)
  })
_sym_db.RegisterMessage(OrderInformation)

Succeeded = _reflection.GeneratedProtocolMessageType('Succeeded', (_message.Message,), {
  'DESCRIPTOR' : _SUCCEEDED,
  '__module__' : 'paymentService_pb2'
  # @@protoc_insertion_point(class_scope:ordermgt.Succeeded)
  })
_sym_db.RegisterMessage(Succeeded)

MailMessage = _reflection.GeneratedProtocolMessageType('MailMessage', (_message.Message,), {
  'DESCRIPTOR' : _MAILMESSAGE,
  '__module__' : 'paymentService_pb2'
  # @@protoc_insertion_point(class_scope:ordermgt.MailMessage)
  })
_sym_db.RegisterMessage(MailMessage)



_PAYMENTSERVICE = _descriptor.ServiceDescriptor(
  name='PaymentService',
  full_name='ordermgt.PaymentService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=622,
  serialized_end=1002,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetPersonalInformation',
    full_name='ordermgt.PaymentService.GetPersonalInformation',
    index=0,
    containing_service=None,
    input_type=_CUSTOMERID,
    output_type=_CUSTOMERINFORMATION,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetPaymentOptions',
    full_name='ordermgt.PaymentService.GetPaymentOptions',
    index=1,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_PAYMENTOPTIONS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CheckPaymentCredentials',
    full_name='ordermgt.PaymentService.CheckPaymentCredentials',
    index=2,
    containing_service=None,
    input_type=_CREDENTIALS,
    output_type=_STATUS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CreatePaymentRecord',
    full_name='ordermgt.PaymentService.CreatePaymentRecord',
    index=3,
    containing_service=None,
    input_type=_ORDERINFORMATION,
    output_type=_SUCCEEDED,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendConfirmation',
    full_name='ordermgt.PaymentService.SendConfirmation',
    index=4,
    containing_service=None,
    input_type=_ORDERINFORMATION,
    output_type=_MAILMESSAGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PAYMENTSERVICE)

DESCRIPTOR.services_by_name['PaymentService'] = _PAYMENTSERVICE

# @@protoc_insertion_point(module_scope)
